"""add_audit_trail_tables

Revision ID: 091129a9535c
Revises: 032e1fddb1f0
Create Date: 2026-01-07 00:31:01.920521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091129a9535c'
down_revision: Union[str, None] = '032e1fddb1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=10), nullable=False),
    sa.Column('bulk_upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bulk_upload_id'], ['bulk_uploads.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_company_id'), 'audit_trail', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_id'), 'audit_trail', ['id'], unique=False)
    op.create_index(op.f('ix_audit_trail_product_id'), 'audit_trail', ['product_id'], unique=False)
    op.create_table('new_audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_unique_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('changes', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=10), nullable=False),
    sa.Column('bulk_upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bulk_upload_id'], ['bulk_uploads.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_audit_trail_company_id'), 'new_audit_trail', ['company_id'], unique=False)
    op.create_index(op.f('ix_new_audit_trail_id'), 'new_audit_trail', ['id'], unique=False)
    op.create_index(op.f('ix_new_audit_trail_product_id'), 'new_audit_trail', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_audit_trail_product_id'), table_name='new_audit_trail')
    op.drop_index(op.f('ix_new_audit_trail_id'), table_name='new_audit_trail')
    op.drop_index(op.f('ix_new_audit_trail_company_id'), table_name='new_audit_trail')
    op.drop_table('new_audit_trail')
    op.drop_index(op.f('ix_audit_trail_product_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_id'), table_name='audit_trail')
    op.drop_index(op.f('ix_audit_trail_company_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
