"""fix_missing_audit_columns

Revision ID: 1d504c212c39
Revises: 493cfb079e49
Create Date: 2026-01-16 19:05:18.239015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d504c212c39'
down_revision: Union[str, None] = '493cfb079e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_audit_trail', sa.Column('product_name', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_audit_trail', 'product_name')
    # ### end Alembic commands ###
