"""add_staff_id_in_employee_table

Revision ID: 4037fde38c13
Revises: 1953fc218a3e
Create Date: 2025-06-13 02:15:07.261774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4037fde38c13'
down_revision: Union[str, None] = '1953fc218a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('staff_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'staff_id')
    # ### end Alembic commands ###
