"""update models

Revision ID: 493cfb079e49
Revises: 091129a9535c
Create Date: 2026-01-16 16:37:51.812489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493cfb079e49'
down_revision: Union[str, None] = '091129a9535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'company_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_foreign_key(None, 'managers', 'companies', ['company_id'], ['id'])
    op.drop_column('managers', 'company_name')
    op.drop_column('managers', 'company_size')
    op.add_column('new_audit_trail', sa.Column('product_name', sa.String(), nullable=False))
    op.alter_column('products', 'company_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.drop_column('products', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manager_id', sa.NUMERIC(), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'managers', ['manager_id'], ['id'])
    op.alter_column('products', 'company_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('new_audit_trail', 'product_name')
    op.add_column('managers', sa.Column('company_size', sa.INTEGER(), nullable=True))
    op.add_column('managers', sa.Column('company_name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'managers', type_='foreignkey')
    op.alter_column('managers', 'company_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
